language: r
cache: packages
sudo: true

pandoc: false

before_install:
  - sudo apt-get update -y 
  - sudo apt-get install build-essential software-properties-common -y 
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y 
  - sudo apt-get update -y 
  - sudo apt-get install gcc-7 g++-7 -y 
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7 
  - sudo update-alternatives --config gcc

before_script:
  - make tests

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
